---
- name: Start docker
  service:
    name: "docker"
    state: started

- name: pulling image
  docker_image:
    name: node
    tag: latest
    source: pull

- name: Obtaining project from github
  git: clone=true repo={{ app_repository }} dest={{  app_destination  }}


- name: Show dir
  shell: 
    chdir: "~/{{ app_destination }}" 
    cmd: ls

- name: install packages
  shell: 
    chdir: "~/{{ app_destination }}" 
    cmd: "npm install"

- name: Build app
  shell: 
    chdir: "~/{{ app_destination }}" 
    cmd: "npm run build"

- name: start app inside a container
  docker_container:
    name: "{{ container_name }}"
    image: node:latest
    state: started
    exposed_ports:
      - "{{ container_port }}"
    ports:
      - "{{ container_port }}:{{ app_port }}"
    volumes:
      - "~/{{ app_destination }}:/app"
    working_dir: /app
    command: "npm run start:prod"
  register: app_status

- name: show container status
  debug: var=app_status


- name: get container logs
  shell: 
    cmd: "docker logs {{ container_name }}" 
  register: container_logs

- name: show container status
  debug: var=container_logs
...