---
- name: Get project from git
  git:
    repo: {{app_repository}}
    dest: {{app_destination}}
    clone: true

- name: Install globally quasar
  shell:
    cmd: npm i -g @quasar/cli
    shdir: {{app_destination}}

- name: Install dependancies
  shell:
    cmd: npm Install
    chdir: {{app_destination}}
...
